### ISSUE TITLE
Use uintptr_t for casting pointers

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#110]
KokkosExp_SharedAlloc.hpp - fix this (unsigned long)

**Comment by nmhamster** [comment]
Can you describe the error/bug for this issue?

**Comment by hcedwar** [comment]
With the exception of Windows every compiler has sizeof(void*) == sizeof(unsigned long).
For portability all casts between pointer and integer types should use the C99 'uintptr_t' integer type, which the C99 language standard states *must* match size.

**Comment by crtrott** [comment]
Isn't that fixed now on Develop?

**Comment by ndellingwood** [comment]
Yes, I amended a previous commit to fix formatting issues on Clang compiler. 
I'll close the issue (if I'm able), I'm still getting acquainted to using GitHub sorry for any workflow mistakes.

In case extra info is necessary to check:
The amended commit was submitted for pull request on Oct 16, sha 467fb78
It was merged Oct 19 as request #116, sha 6e3081a
