### ISSUE TITLE
Nightly test failure: Illegal instruction in Random_XorShift64 with intel/17.0.4 and Threads backend

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#4113]
The Random_XorShift64 unit test began failing with the Threads backend with intel/17.0.4.20170411 and debug mode. This does not occur with intel/17.0.1. ~~This followed after merge of changes from PRs #4088 and #4089, will need to bisect on those changes to pinpoint more carefully, though~~ unclear why those changes would trigger this in one version of intel/17 and not another (suspect compiler bug).

Failure output:
```
[ RUN      ] threads.Random_XorShift64
Test Seed:1624306732630882512
Density 3D: 0 0.00211383 0.000170936 || 0.051031 1e+64 -1e+64
Test Scalar=half
 -- Testing randomness properties

Program received signal SIGILL, Illegal instruction.
```

Running the test through gdb gave this output:
```
Program received signal SIGILL, Illegal instruction.
0x00000000004d3503 in Kokkos::Impl::ParallelReduce<Test::Impl::test_random_functor<Kokkos::Random_XorShift64_Pool<Kokkos::Threads>, float>, Kokkos::RangePolicy<Kokkos::Threads>, Kokkos::InvalidType, Kokkos::Threads>::exec (exec=..., arg=0x2545f4914f6cdd1d)
    at /ascldap/users/ndellin/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp:207
207	  return __sync_fetch_and_add(dest, val);

(gdb) list
202	#else
203	inline int atomic_fetch_add(volatile int* const dest, const int val) {
204	#if defined(KOKKOS_ENABLE_RFO_PREFETCH)
205	  _mm_prefetch((const char*)dest, _MM_HINT_ET0);
206	#endif
207	  return __sync_fetch_and_add(dest, val);
208	}
209	#endif
210	
211	inline long int atomic_fetch_add(volatile long int* const dest,
```

Reproducer:
```
$KOKKOS_PATH/generate_makefile.bash --with-devices=Pthread --arch=SKX –compiler=icpc --cxxflags="-g -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="14" --kokkos-path=$KOKKOS_PATH --no-examples --with-options=enable_large_mem_tests --debug
```

**Comment by masterleinad** [comment]
> This followed after merge of changes from PRs #4088 and #4089,

This doesn't make a lot of sense. Both pull requests only touched `SYCL` files.

**Comment by ndellingwood** [comment]
@masterleinad agreed, I had missed another PR that went in that likely was change #4102. Doesn't make sense that those changes should cause the compiler error (reminds me of #3957), I'm guessing touching a compiler error with this version of intel/17

**Comment by ndellingwood** [comment]
@masterleinad I guess I got turned around with too many Jenkins windows, I made a mistake in navigating to pinpoint when the failure began. It predates the PRs I've mentioned, sorry for the confusion. Intel testing was down for a stretch of time, there will not be a clear indicator at which change the failure began based on testing history

**Comment by ndellingwood** [comment]
I tried a simple test calling a parallel_for with all threads writing to the same location of a View using `atomic_fetch_add` but no luck reproducing in isolated case so far.

**Comment by ndellingwood** [comment]
* Recent failure 08/17/2021 (intel/17.0.4, Pthreads backend, SKX arch, Blake testbed)

This test had passed for at least two weeks of previous nightly runs, @crtrott

**Comment by crtrott** [comment]
I think this was fixed in #4137

**Comment by ndellingwood** [comment]
@crtrott that resolved the failure for a spell, but the failure resurfaced 8/17/2021 and has been failing consistently since

**Comment by ndellingwood** [comment]
The `threads.Random_XorShift1024_0` is still failing with intel/17.0.4 after merge of #4270 :(

**Comment by crtrott** [comment]
this is not desul atomics btw. the error message there initially indicates use of the old atomics.

**Comment by PhilMiller** [comment]
Fix released in 3.6
