### ISSUE TITLE
Kernels using TeamPolicy with certain dimensions won't execute

### ISSUE THREAD

**Issue by euphoricpoptarts** [kokkos/kokkos#4531]
There seems to be an issue when using a TeamPolicy with a league size X and team size Y whenever X*Y mod 2^32 > 2^31. This occurs even when the IndexType used by the policy is an int64_t or uint64_t. See the below code which replicates the issue:
```
#include <Kokkos_Core.hpp>

using Device = Kokkos::Device<Kokkos::DefaultExecutionSpace, typename Kokkos::DefaultExecutionSpace::memory_space>;
using team_policy_t = Kokkos::TeamPolicy<Kokkos::IndexType<uint64_t>, typename Device::execution_space>;
using member_t = typename team_policy_t::member_type;

struct range_count {
    KOKKOS_INLINE_FUNCTION
    void operator() (const member_t& t, uint64_t& update) const {
        const uint64_t i = t.league_rank();
        Kokkos::single(Kokkos::PerTeam(t), [&] (){
            update++;
        });
    }
};

void driver(){
    range_count count_functor;
    uint64_t range = (2LU << 23) - 1;
    uint64_t result = 0;
    Kokkos::parallel_reduce("count range", team_policy_t(range, 128), count_functor, result);
    //correct
    printf("Number of teams executed for range %lu: %lu\n", range, result);
    range = 2LU << 23;
    Kokkos::parallel_reduce("count range", team_policy_t(range, 128), count_functor, result);
    //incorrect
    printf("Number of teams executed for range %lu: %lu\n", range, result);
    range = (2LU << 24);
    Kokkos::parallel_reduce("count range", team_policy_t(range, 128), count_functor, result);
    //incorrect
    printf("Number of teams executed for range %lu: %lu\n", range, result);
    range = (2LU << 24) + 1;
    Kokkos::parallel_reduce("count range", team_policy_t(range, 128), count_functor, result);
    //correct
    printf("Number of teams executed for range %lu: %lu\n", range, result);
}

int test() {
    Kokkos::initialize();
    {
        driver();
    }
    Kokkos::finalize();
    return 0;
}

int main(int argc, char** args) {
    return test();
}
```

**Comment by euphoricpoptarts** [comment]
I should clarify this only replicates the issue when the DefaultExecutionSpace is Cuda

**Comment by masterleinad** [comment]
#4532 should fix this issue.

**Comment by masterleinad** [comment]
> Morning @masterleinad -- Thank you for chiming in. Does this item need to be discussed in our Wed. meeting?

It needs reviews.

**Comment by euphoricpoptarts** [comment]
@masterleinad The PR #4532 fixes this particular case, but if instead I use `Kokkos::IndexType<int32_t>` I still get incorrect results. It would be nice if I didn't have to use `Kokkos::IndexType<int64_t>` or `Kokkos::IndexType<uint64_t>` since the league size I'm using still fits within an `int32_t`. Maybe the below line in the PR:
```
const auto nwork = static_cast<typename Policy::index_type>(m_league_size) * m_team_size;
```
Could be something like:
```
const uint64_t nwork = static_cast<uint64_t>(m_league_size) * m_team_size;
```

**Comment by masterleinad** [comment]
@euphoricpoptarts We actually don't need to multiply `league_size` and `team_size` at all. Please have a look at the latest commit in #4352.

**Comment by euphoricpoptarts** [comment]
@masterleinad That's perfect! Thanks for looking into this!

**Comment by euphoricpoptarts** [comment]
@masterleinad One more thing on this issue. If the Execution Space is `Kokkos::OpenMP`, then the kernel won't execute for a league size X and team size Y if X*Y mod 2^32 = 0. For example:
```
range = (1LU << 28);
Kokkos::parallel_reduce("count range", team_policy_t(range, 16), count_functor, result);
```
`result` here will be 0.

**Comment by euphoricpoptarts** [comment]
@masterleinad Just tried out the commit, it looks like it fixed the issue.

**Comment by ajpowelsnl** [comment]
Morning @euphoricpoptarts and @masterleinad  -- Are we all set with this fix?  If so, may I close the issue?

**Comment by masterleinad** [comment]
> Morning @euphoricpoptarts and @masterleinad -- Are we all set with this fix? If so, may I close the issue?

No, #4532 is not merged yet.

**Comment by ajpowelsnl** [comment]
Morning @masterleinad -- Given the "linked pull request" message above, would it be OK to close this issue now, or mark it "InDevelop?"

**Comment by masterleinad** [comment]
> Morning @masterleinad -- Given the "linked pull request" message above, would it be OK to close this issue now, or mark it "InDevelop?"

No, it's still not merged. If we decide that the pull request doesn't do what we want and we discard it, the issue is still not resolved.

**Comment by ajpowelsnl** [comment]
> > Morning @masterleinad -- Given the "linked pull request" message above, would it be OK to close this issue now, or mark it "InDevelop?"
> 
> No, it's still not merged. If we decide that the pull request doesn't do what we want and we discard it, the issue is still not resolved.

Ahh...OK. Thanks for the guidance -- I had not thought about a PR for a bug being a provisional solution, but that's probably how it should be viewed until it is merged into develop.

**Comment by crtrott** [comment]
@masterleinad is that the merged thing above?

**Comment by euphoricpoptarts** [comment]
If the #4532 PR is merged then I think we can close this issue.

**Comment by masterleinad** [comment]
> @masterleinad is that the merged thing above?

Yes.
