### ISSUE TITLE
Nightly build failures on develop with intel/19, "missing return statement at end of non-void function"

### ISSUE THREAD

**Issue by ndellingwood** [kokkos/kokkos#5432]
**Describe the bug**
Nightly builds with intel/19 (all backends) fail to compile with output:
```
14:28:58 /home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/src/impl/Kokkos_ViewCtor.hpp(289): error #1011: missing return statement at end of non-void function "Kokkos::Impl::with_properties_if_unset(const Kokkos::Impl::ViewCtorProp<P...> &, const Property &, const Properties &...) [with P=<std::__cxx11::string>, Property=std::__cxx11::string, Properties=<>]"
14:28:58   }
14:28:58   ^
14:28:58           detected during:
14:28:58             instantiation of "auto Kokkos::Impl::with_properties_if_unset(const Kokkos::Impl::ViewCtorProp<P...> &, const Property &, const Properties &...) [with P=<std::__cxx11::string>, Property=std::__cxx11::string, Properties=<>]" at line 1408 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/src/Kokkos_View.hpp"
14:28:58             instantiation of "Kokkos::View<DataType, Properties...>::View(const Kokkos::Impl::ViewCtorProp<P...> &, const std::enable_if_t<<expression>, Kokkos::ViewTraits<DataType, Properties...>::array_layout> &, Kokkos::View<DataType, Properties...>::check_input_args) [with DataType=int *, Properties=<exec_space>, P=<std::__cxx11::string>]" at line 1567 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/src/Kokkos_View.hpp"
14:28:58             instantiation of "Kokkos::View<DataType, Properties...>::View(const Label &, std::enable_if_t<Kokkos::Impl::is_view_label<Label>::value, const size_t={unsigned long}>, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}, size_t={unsigned long}) [with DataType=int *, Properties=<exec_space>, Label=char [6]]" at line 25 of
14:28:58                       "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/perf_test/test_atomic_minmax_simple.cpp"
14:28:58             instantiation of "void test<T>(int) [with T=int]" at line 224 of "/home/jenkins/node/workspace/kokkos_osrhel7_intel_1905_openmp_pthread_serial/kokkos/core/perf_test/test_atomic_minmax_simple.cpp"
```

Commits merged when failure began:

Remove code only used by ROCm < 5.0 ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/448/changes#0fb2f480b83f11ce3697277475642534ef660424) / [githubweb](https://github.com/kokkos/kokkos/commit/0fb2f480b83f11ce3697277475642534ef660424))
    Don't rely on synchronization behavior of default stream in CUDA and HIP ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/448/changes#397a6bc47f14e7ab1251ba7614bcf4ff4adae796) / [githubweb](https://github.com/kokkos/kokkos/commit/397a6bc47f14e7ab1251ba7614bcf4ff4adae796))
    Remove XL compiler support (#5349) ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/448/changes#c4c9bfcf07c830153f0e1455387f1dad0ef6a8b0) / [githubweb](https://github.com/kokkos/kokkos/commit/c4c9bfcf07c830153f0e1455387f1dad0ef6a8b0))
    Remove dummy arguments for ViewCtorProp (#5314) ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/448/changes#338b4585712c0ab5f4837772954a3204d9f6f150) / [githubweb](https://github.com/kokkos/kokkos/commit/338b4585712c0ab5f4837772954a3204d9f6f150))
    Dispatch Kokkos::sort(Kokkos::View) to std::sort (#5372) ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/448/changes#30c17a8e29557a6192a78d95e2fbbaad6b12dc41) / [githubweb](https://github.com/kokkos/kokkos/commit/30c17a8e29557a6192a78d95e2fbbaad6b12dc41))
    Enable Android x86_64 support (#5423) ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/448/changes#4e2c540fc0847bf0a000ce14bef7a3abf044dc78) / [githubweb](https://github.com/kokkos/kokkos/commit/4e2c540fc0847bf0a000ce14bef7a3abf044dc78))
    Silence warnings about valueView being unused (#5421) ([details](https://jenkins-son.sandia.gov/job/kokkos_osrhel7_intel_1905_openmp_pthread_serial/448/changes#c82eb33517cd2f641ff52c420f56c8ebc09b39bc) / [githubweb](https://github.com/kokkos/kokkos/commit/c82eb33517cd2f641ff52c420f56c8ebc09b39bc))

The list indicates that #5314 may have triggered, though the change could have merged a couple days before (nightly builds were failing due to -Werror until merge of #5421 which also merged when the error began)

**Please also include the following items to support reproducing the bug**
**Reproducer**:
```bash
$KOKKOS_PATH/generate_makefile.bash --with-devices=Serial  --compiler=icpc --cxxflags="-O3 -Wall -Wunused-parameter -Wshadow -pedantic -Werror -Wsign-compare -Wtype-limits -Wuninitialized " --cxxstandard="17" --ldflags=""  --kokkos-path=$KOKKOS_PATH  --no-examples   --with-options=enable_large_mem_tests
```

**Comment by dalg24** [comment]
Same issue as #5426

**Comment by dalg24** [comment]
https://godbolt.org/z/q7vE9EGYs

**Comment by masterleinad** [comment]
Fixed in #5433.

**Comment by ndellingwood** [comment]
Reopening, still seeing the issue 

```
/ascldap/users/ndellin/kokkos-1/core/src/impl/Kokkos_ViewCtor.hpp(304): error #1011: missing return statement at end of non-void function "Kokkos::Impl::with_properties_if_unset(const Kokkos::Impl::ViewCtorProp<P...> &, const Property &, const Properties &...) [with P=<std::__cxx11::string>, Property=std::__cxx11::string, Properties=<>]"
  }
```

**Comment by ndellingwood** [comment]
Issue still present as of SHA d0f710de8010a476abb93f9f63a0b0bc27f7541f

**Comment by ndellingwood** [comment]
So far the only way to suppress the warnings I found is to add the `-diag-disable=1011,-diag-disable=869` flags; I submitted a PR to update the nightly testing script to include these flags for now

**Comment by ndellingwood** [comment]
Also seeing the issue with 2021.5.0

```
bash-4.2$ icpc --version
icpc (ICC) 2021.5.0 20211109
Copyright (C) 1985-2021 Intel Corporation.  All rights reserved.
```

**Comment by masterleinad** [comment]
Looks like some version of std::unreachable would also do the trick (at least for ICC), see [godbolt.org/z/99T84x4cb](https://godbolt.org/z/99T84x4cb).

**Comment by ndellingwood** [comment]
This is still an issue in nightly builds, unless warning suppression flags are used

**Comment by dalg24** [comment]
Please confirm what build and what warning.

**Comment by ndellingwood** [comment]
@dalg24 the intel/19 builds with -Werror, same warning as in OP e.g.
```
/home/jenkins/blake-new/workspace/Kokkos_develop_blake_intel_openmp_pthread_serial_195281/kokkos/core/src/impl/Kokkos_ViewCtor.hpp(272): error #869: parameter "property" was never referenced
                                const Property &property,
```

**Comment by masterleinad** [comment]
Ah, but that's different, right? We should just mark `property` as `maybe_unused`.

**Comment by ndellingwood** [comment]
> Ah, but that's different, right?

Right, I made a mistake updating this issue (thought it was tracking the -Werror that weren't resolved via push and pop macros to suppress the warning)

**Comment by PhilMiller** [comment]
Issue was develop-only as noted, so closing.
