### ISSUE TITLE
Enabling ARM NEON and CUDA in the same build results in build errors for SIMD

### ISSUE THREAD

**Issue by scothalverson** [kokkos/kokkos#7483]
**Describe the bug**

@diehlpk and I are working on a build of a Kokkos application that will use both NEON and CUDA.  When attempting to build Kokkos with both enabled, we see errors like the following:

[ 99%] Building CXX object simd/unit_tests/CMakeFiles/Kokkos_UnitTest_SIMD.dir/TestSIMD.cpp.o
/cm/local/apps/gcc/13.1.0/lib/gcc/aarch64-unknown-linux-gnu/13.1.0/include/arm_neon.h(46): error: identifier "__Poly8x8_t" is undefined
  typedef __Poly8x8_t poly8x8_t;

From what I can tell, this is happening as a result of NVCC being used to compile simd/src/Kokkos_SIMD.hpp, which includes arm_neon.h from GCC if KOKKOS_ARCH_ARM_NEON is enabled.  I believe a potential solution to this is to also check that __CUDACC__ is not defined, resulting in the NEON headers and types only being included in the host side pass for NVCC.  

as an example,  replacing 
`#if defined(KOKKOS_ARCH_ARM_NEON)`
with
`#if defined(KOKKOS_ARCH_ARM_NEON) && !defined(__CUDACC__)`
where that (or the corresponding elif) appear in Kokkos_SIMD.hpp allows the build to finish, and pass all tests.  

Its not clear to me if this would also be an issue for other vector implementations included in the same file (AVX, AVX2, AVX512).

**Please include the following for a minimal reproducer**

1. Compilers (with versions)
host: GCC 13
device: NVCC 12.6
3. Kokkos release or commit used (i.e., the sha1 number)
e6e5c4598d16d756db62225ab7f937ee833bd660
5. Platform, architecture and backend
Grace Hopper (Arm Neoverse V2 + Hopper)
7. CMake configure command
Kokkos_ENABLE_CUDA=ON Kokkos_ARCH_ARMV9_GRACE=ON Kokkos_ARCH_HOPPER90=ON CMAKE_CXX_COMPILER=g++ Kokkos_ENABLE_TESTS=ON
9. Output from CMake configure command
/cm/local/apps/gcc/13.1.0/lib/gcc/aarch64-unknown-linux-gnu/13.1.0/include/arm_neon.h(46): error: identifier "__Poly8x8_t" is undefined
  typedef __Poly8x8_t poly8x8_t;
11. Minimum, complete code needed to reproduce the bug
Kokkos tests (SIMD) are enough to exhibit the problem
13. Command line needed to reproduce the bug
make

**Comment by masterleinad** [comment]
AFAIK, `__CUDACC__` is always defined when compiling via `nvcc_wrapper` so the proposed workaround basically disables ARM NEON support.

**Comment by cwpearson** [comment]
Does `__CUDA_ARCH__` discriminate the way we need?

**Comment by masterleinad** [comment]
> Does `__CUDA_ARCH__` discriminate the way we need?

That would also mean that we get different default SIMD types based on the compile path.

**Comment by scothalverson** [comment]
Interesting, I did not know __CUDACC__ is always enabled with the wrapper.  I would assume __CUDA_ARCH__ is similarly defined, no?  

I don't know enough about how Kokkos uses SIMD types - would they ever be used in a CUDA execution space?  If so that could be a problem, and may prevent this from working at all.

**Comment by masterleinad** [comment]
> Interesting, I did not know __CUDACC__ is always enabled with the wrapper. I would assume __CUDA_ARCH__ is similarly defined, no?

`nvcc_wrapper` is basically doing `nvcc -x cu` for all files. `__CUDA_ARCH__` is only defined in the device compilation pass so it's not always defined.

> I don't know enough about how Kokkos uses SIMD types - would they ever be used in a CUDA execution space? If so that could be a problem, and may prevent this from working at all.

Yes, but only a scalar SIMD type is supported in device code.

**Comment by crtrott** [comment]
Which Kokkos version are you working with and which compiler?

**Comment by crtrott** [comment]
How do you get to NEON then given this git-blame on our kokkos_arch.cmake? 
```
73b6d032b6 (Cédric Chevalier   2024-07-29 15:50:46 +0200  682) # FIXME_NVCC nvcc doesn't seem to support Arm Neon.
0247634f35 (Daniel Arndt       2024-09-27 21:36:12 -0400  683) if(KOKKOS_ARCH_ARM_NEON AND KOKKOS_CXX_COMPILER_ID STREQUAL NVIDIA)
0247634f35 (Daniel Arndt       2024-09-27 21:36:12 -0400  684)   unset(KOKKOS_ARCH_ARM_NEON)
0247634f35 (Daniel Arndt       2024-09-27 21:36:12 -0400  685) endif()
```

**Comment by crtrott** [comment]
https://github.com/kokkos/kokkos/pull/7158 here we disabled NEON for NVCC.

**Comment by crtrott** [comment]
I really don't get it I am compiling with your commands and your SHA and I don't get KOKKOS_ARCH_ARM_NEON defined.

**Comment by scothalverson** [comment]
are you setting CXX=g++?  That's the only thing I think we did that wasn't standard or explicit in the issue info.  I'll check later how we actually invoked this.

**Comment by scothalverson** [comment]
@diehlpk - the goal of this is to use GPU + SIMD CPU.  should this be doable with SVE2?

**Comment by diehlpk** [comment]
> #7158 here we disabled NEON for NVCC.

@crtrott We enabled NEON again since @scothalverson wants to fix the issue that we can not use NEON with NVCC. So we reverted https://github.com/kokkos/kokkos/pull/7158 partially.

**Comment by diehlpk** [comment]
> @diehlpk - the goal of this is to use GPU + SIMD CPU. should this be doable with SVE2?

@scothalverson For now I just wanted to fix the NEON compilation.

**Comment by crtrott** [comment]
Yeah so I think this is in NVIDIA's court to fix it.

**Comment by crtrott** [comment]
So summarize: we know this is broken, NVIDIA knows it is broken and we need to wait for a fix.

**Comment by dslarm** [comment]
FYI - this is fixed in CUDA 12.8 - but only if using GCC < 12 :-(

**Comment by ocaisa** [comment]
Do you know what is the status of this with CUDA 12.9?

EDIT: Our testing shows it still exists there (GCC 13)

**Comment by masterleinad** [comment]
> FYI - this is fixed in CUDA 12.8 - but only if using GCC < 12 :-(

I seem to be able to compile with CUDA 12.8 and gcc-12.2.1 as well (while allowing using ARM NEON for SIMD).

**Comment by ocaisa** [comment]
As yet unverified but we have been told this _should_ be fixed with CUDA 13.1

**Comment by JBludau** [comment]
I linked a PR that at enables NEON on cuda >=12.8 with host compilers that support it. But up to cuda 13.0.2 I still see a lack of SVE support. @diehlpk @scothalverson could you check #8667 ?

**Comment by masterleinad** [comment]
As of Cuda 13.1, SVE is still not supported with `nvcc`, see https://github.com/kokkos/kokkos/pull/8801.
