### ISSUE TITLE
Cannot configure on summit dev

### ISSUE THREAD

**Issue by Rombur** [kokkos/kokkos#897]
I can't configure Trilinos on summitdev with XL compiler (see error below). It works fine with gcc and I can configure Trilinos if I use XL but set `NVCC_WRAPPER_DEFAULT_COMPILER` to `g++`. 

```-- CMAKE_C_COMPILER_ID='XL'
-- CMAKE_C_COMPILER_VERSION='13.1.5'
-- The CXX compiler identification is XL 13.1.5
-- Check for working CXX compiler: /sw/summitdev/spectrum_mpi/10.1.0.2-20161221c/xl-20161123/bin/mpicxx
-- Check for working CXX compiler: /sw/summitdev/spectrum_mpi/10.1.0.2-20161221c/xl-20161123/bin/mpicxx -- broken
CMake Error at /autofs/nccs-svm1_sw/summitdev/.swci/0-core/opt/spack/20170405/linux-rhel7-ppc64le/gcc-4.8.5/cmake-3.6.1-atrfhdmrguevm377m63pzxqg5kh3bdr2/share/cmake-3.6/Modules/CMakeTestCXXCompiler.cmake:54 (mess
age):
  The C++ compiler
  "/sw/summitdev/spectrum_mpi/10.1.0.2-20161221c/xl-20161123/bin/mpicxx" is
  not able to compile a simple test program.

  It fails with the following output:

   Change Dir: /ccs/home/turcksin/summitdev/Trilinos/build_xl/CMakeFiles/CMakeTmp

  

  Run Build Command:"/usr/bin/gmake" "cmTC_4b312/fast"

  /usr/bin/gmake -f CMakeFiles/cmTC_4b312.dir/build.make
  CMakeFiles/cmTC_4b312.dir/build

  gmake[1]: Entering directory
  `/autofs/nccs-svm1_home1/turcksin/summitdev/Trilinos/build_xl/CMakeFiles/CMakeTmp'


  Building CXX object CMakeFiles/cmTC_4b312.dir/testCXXCompiler.cxx.o

  /sw/summitdev/spectrum_mpi/10.1.0.2-20161221c/xl-20161123/bin/mpicxx -+ -g
  -arch=sm_60 -lineinfo -std=c++11 --expt-extended-lambda -Xcudafe
  --diag_suppress=conversion_function_not_usable -Xcudafe
  --diag_suppress=cc_clobber_ignored -Xcudafe
  --diag_suppress=code_is_unreachable -o
  CMakeFiles/cmTC_4b312.dir/testCXXCompiler.cxx.o -c
  /ccs/home/turcksin/summitdev/Trilinos/build_xl/CMakeFiles/CMakeTmp/testCXXCompiler.cxx


  /sw/summitdev/xl/20170109/xlC/13.1.5/bin/.orig/xlc++: error: 1501-259 The
  -+ option cannot be used with x.

  gmake[1]: *** [CMakeFiles/cmTC_4b312.dir/testCXXCompiler.cxx.o] Error 40

  gmake[1]: Leaving directory
  `/autofs/nccs-svm1_home1/turcksin/summitdev/Trilinos/build_xl/CMakeFiles/CMakeTmp'


  gmake: *** [cmTC_4b312/fast] Error 2```

**Comment by ibaned** [comment]
@Rombur please post your full configuration command or script.

@nmhamster

**Comment by nmhamster** [comment]
@ibaned @Rombur - Kokkos does not work with the IBM XL 13.X series of compilers. There is essentially a known set of issues which IBM has fixed in the forthcoming XL compiler series that will prevent compilation and linking of Kokkos-based code. We can confirm that IBM's current XL beta products do work with Kokkos and correctly pass tests for OpenMP on the POWER host.

**Comment by Rombur** [comment]
@nmhamster thanks for the answer.

**Comment by dholladay00** [comment]
I am still seeing this issue with 16.1.1, any ideas on when/which version this fix is coming?
