### ISSUE TITLE
Preprocessor check at top of KokkosCore_config.h breaks internal customer's build process

### ISSUE THREAD

**Issue by mhoemmen** [kokkos/kokkos#978]
`$ git blame core/cmake/KokkosCore_config.h`
```
82a0d275 (Dan Ibanez     2017-05-11 12:30:53 -0600   1) #if !defined(KOKKOS_MACROS_HPP) || defined(KOKKOS_CORE_CONFIG_H)
82a0d275 (Dan Ibanez     2017-05-11 12:30:53 -0600   2) #error "Don't include KokkosCore_config.h directly; include Kokkos_Macros.hpp instead."
82a0d275 (Dan Ibanez     2017-05-11 12:30:53 -0600   3) #else
^d0932b0 (Carter Edwards 2015-04-09 09:28:05 -0600   4) #define KOKKOS_CORE_CONFIG_H
82a0d275 (Dan Ibanez     2017-05-11 12:30:53 -0600   5) #endif
```
Sorry @ibaned :(  I know it's horrible, but could we please not do this error check here?  It makes Rich Drake's life hard and it's making my life hard now too.  I'll submit a PR if it's OK.

Obligatory xkcd: https://xkcd.com/1172/

**Comment by mhoemmen** [comment]
btw `KOKKOS_FOR_SIERRA` is no longer used.

**Comment by ibaned** [comment]
This wasn't really my idea alone, I just implemented it. There are really good reasons for this. Can we actually get some details from yourself and @rrdrake about why including `Kokkos_Macros.hpp` doesn't work as a solution?

**Comment by ibaned** [comment]
@dsunder

**Comment by rrdrake** [comment]
The core difficulty is the hand off between build systems - TriBITS to bjam.  We recognize this and have plans to address it, but it is the reality right now.  The bjam config file defines CPP macros in order to turn on/off options in Trilinos based on the platform/compiler combination.

More specifically, we are defining KOKKOS_CORE_CONFIG_H in order to prevent the macros in that file from being set.  Instead, we define (on the compile line) the macros that *would* get defined appropriately based on the platform/compiler.

That CPP logic at the top of the file prevents us from using this (admittedly problematic) method to control the macro definitions.

**Comment by ibaned** [comment]
So you have bjam calling the Trilinos configure process, but for some reason the TriBITS options are not flexible enough, so you define `KOKKOS_CORE_CONFIG_H` so that the TriBITS-generated `KokkosCore_config.h` is ignored in favor of other macros you define?

I think its fair to say that the integration of Kokkos into this application is important enough for us to invest time in integrating them correctly.

Could you give us more details on exactly what macros are overriden, where it is that we lack sufficient flexibility? (in other words, what would go wrong if you used the generated `KokkosCore_config.h`). I'm sure Kokkos and/or TriBITS could be modified so they are easier to use in your build system.

Not only is Kokkos used by other codes that don't even have `KokkosCore_config.h`, but TriBITS is also undergoing changes to integrate the Kokkos machinery for architecture detection. All this is evidence we're open to changing these systems so you see a nice interface, instead of forcing you to use these workarounds. We need to know the specifics of what has to change, though.

**Comment by ibaned** [comment]
mentioning the folks doing the TriBITS work: @bartlettroscoe @kruger

**Comment by ibaned** [comment]
Also just FYI, Boost themselves are [moving to CMake](https://lists.boost.org/boost-interest/2017/07/0162.php). That doesn't change much for any of us in the short term, but it is the long-term direction.

**Comment by mhoemmen** [comment]
@ibaned wrote:
> (in other words, what would go wrong if you used the generated KokkosCore_config.h)

The essence is that Sierra runs CMake once, but then controls macros directly to change the configuration for different platforms and build options (e.g., enabling OpenMP).  (There's a reason I linked to that xkcd cartoon -- people know this is broken but it's not an option to fix right now.)  Thus, Sierra cannot just include the generated KokkosCore_config.h, because it won't necessarily have the right macro settings.

**Comment by mhoemmen** [comment]
I also want to emphasize that Sierra does not use the `KOKKOS_FOR_SIERRA` option any more.

**Comment by ibaned** [comment]
>Sierra runs CMake once, but then controls macros directly to change the configuration for different platforms and build options

I see. In that case, maybe what we should do is remove the old `KOKKOS_FOR_SIERRA` logic and replace it with new logic that just accepts new command-line macros from Sierra that override the current ones?

Maybe even (to keep the existing workaround behavior) a `KOKKOS_IGNORE_CORE_CONFIG_H` option that will `#ifdef` out the whole file. The point is, we still want to protect non-advanced users from including this file without knowing its problematic, which is a mistake I myself have made several times. So the override should be something new, not the existing `KOKKOS_CORE_CONFIG_H` that is used for safety checking.

**Comment by mhoemmen** [comment]
@rrdrake I'm curious, why did Sierra stop using `KOKKOS_FOR_SIERRA`?  It seems like this could fix the `KokkosCore_config.h` issue at least,  even though it's not a very general solution.

**Comment by rrdrake** [comment]
Not sure why KOKKOS_FOR_SIERRA is not used anymore.  I would have to ask Paul W., Brent, or Mike Glass the history there.

**Comment by rrdrake** [comment]
In any case, I would be receptive to a solution that uses KOKKOS_FOR_SIERRA as separate logic to work around this issue for the time being.

**Comment by ibaned** [comment]
If you're willing to start using `KOKKOS_FOR_SIERRA` again, I've moved the conditionals around so that it should work the way it used to (`#ifdef`s out the whole file) in PR #984

**Comment by mhoemmen** [comment]
Thanks @ibaned !  btw you totally didn't have to do this.  I was mainly asking for permission :-) .

**Comment by ibaned** [comment]
Eh, its a small change. We just missed the deadline for the current promotion though, so we may have to wait till the next one (or drop a patch on the snapshot after it goes in Trilinos).

**Comment by mhoemmen** [comment]
@ibaned It's totally OK, we can always patch the Sierra version if we need to.

**Comment by ibaned** [comment]
The changes are in Kokkos develop, please let us know if it works for you.

**Comment by ibaned** [comment]
Hmm I also just spotted this in `Kokkos_Macros.hpp`:
```cpp
#ifndef KOKKOS_DONT_INCLUDE_CORE_CONFIG_H
  #include <KokkosCore_config.h>
#endif
```
I suspect this was also for Sierra, for some reason this problem has been solved a dozen different ways already.

**Comment by mhoemmen** [comment]
> The changes are in Kokkos develop, please let us know if it works for you.

Thanks @ibaned !  Unfortunately we're still having some unrelated trouble getting recent Kokkos to build with Sierra, so we haven't had a chance to test this yet.  The 27 July Kokkos promotion broke stuff and I can't tell if it's just Sierra doing silly things (e.g., aggressive forward declarations) or if something actually broke.  See Sierra ticket 17124 for details.

**Comment by hcedwar** [comment]
@mhoemmen Please give a link to referenced ticket via email to Dan and I (not github).  We plan to do another quick promotion very soon (this week?) and would be good to have this diagnosed and addressed if root cause is Kokkos issue.

**Comment by mhoemmen** [comment]
@hcedwar @dsunder I just replied to your e-mail with some sample build errors and a possible cause.

**Comment by mhoemmen** [comment]
@mhoemmen wrote:
> The 27 July Kokkos promotion broke stuff....

btw we figured out how to fix it.
